### ISSUE TITLE
Check in the responder handler function, whether the response buffer is NULL

### ISSUE THREAD

**Issue by sampmisr** [openbmc/pldm#2]
in the encode_*_resp() functions we are checking if the response buffer is not allocated/NULL. if so then returning PLDM_ERROR_INVALID_DATA. but we are currently not checking that return code in the responder/handler functions. The responder should check the return type and send appropriate return code back to the caller.
This has to be addressed throughout the repo.

**Comment by dkodihal** [comment]
Fixed with https://github.com/openbmc/pldm/commit/8b9766599f09b7dc5c2f1def8ff3218e95990b55.
