### ISSUE TITLE
README for pldmtool

### ISSUE THREAD

**Issue by manojkiraneda** [openbmc/pldm#20]
In the current state, the pldm tool does provide the implemented commands in the help section of the tool, but as a whole i feel having a README in the pldmtool folder that states the following can help a newbie to understand more about the tool and pldm a as a whole.

- What does it do.
- What are the supported commands as per the pldm spec
- Cheatsheet with some basic commands for some one new to look at
- Some info on how do we frame the pldmtool raw commands.
- Ongoing Development - Future support (so that community can be engaged)

**Comment by manojkiraneda** [comment]
@SrideviRamesh do you think, you can help us with this ?

**Comment by SrideviRamesh** [comment]
@manojkiraneda I will take up this activity. Thanks

**Comment by SrideviRamesh** [comment]
Under review - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/43180

**Comment by manojkiraneda** [comment]
merged, closing the issue.
