### ISSUE TITLE
pldmtool doesn't set the "set request" bit in SetStateSensorStates requests

### ISSUE THREAD

**Issue by ibmzach** [openbmc/pldm#22]
I think it should.

**Comment by williamspatrick** [comment]
Are you planning to make the change?  This sounds trivial enough that it would have been lower effort to make a fix on Gerrit than to open an issue on GH.

**Comment by ibmzach** [comment]
No, it's not trivial for me.

**Comment by manojkiraneda** [comment]
First of all, pldmtool does not support `SetStateSensorStates` command yet. The only supported commands are obtained from the help section in the tool:

```ascii
root@w74-emmc-tacoma:~# pldmtool platform -h
platform type command
Usage: pldmtool platform [OPTIONS] SUBCOMMAND

Options:
  -h,--help                   Print this help message and exit

Subcommands:
  GetPDR                      get platform descriptor records
  SetStateEffecterStates      set effecter states
  SetNumericEffecterValue     set the value for a PLDM Numeric Effecter
  GetStateSensorReadings      get the state sensor readings
```

Assuming that the "set request" bit is present in the `SetStateEffecterStates` command, i did a small check to see if it is being set 

```ascii
root@w74-emmc-tacoma:~# pldmtool platform SetStateEffecterStates -i 1 -c 1 -d `00` 02 -v
Request Message:
08 01 80 02 39 01 00 01 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Success in creating the socket : RC = 4
Success in connecting to socket : RC = 0
Success in sending message type as pldm to mctp : RC = 0
Write to socket successful : RC = 24
Total length:6
Shutdown Socket successful :  RC = 0
Response Message:
08 01 00 02 39 00 
{
    "Response": "SUCCESS"
}
```
Input : -i 1 -c 1 -d 00 02 -v [ -i effecterid -c effectercount -d setrequestbit effecterstate]
Command that is being sent has the request bit set to 0: 08 01 80 02 39 01 00 01 `00` 02

```ascii
root@w74-emmc-tacoma:~# pldmtool platform SetStateEffecterStates -i 1 -c 1 -d `01` 02 -v
Request Message:
08 01 80 02 39 01 00 01 01 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Success in creating the socket : RC = 4
Success in connecting to socket : RC = 0
Success in sending message type as pldm to mctp : RC = 0
Write to socket successful : RC = 24
Total length:6
Shutdown Socket successful :  RC = 0
Response Message:
08 01 00 02 39 00 
{
    "Response": "SUCCESS"
}
```
Input : -i 1 -c 1 -d `01` 02 [ -i effecterid -c effectercount -d setrequestbit effecterstate]
Command that is being sent has the request bit set to 1 : 08 01 80 02 39 01 00 01 `01` 02 

In both the cases 
- when we set the setrequest bit, it is being set, and the effecter is set with the new value
- when we reset the setrequest bit it is reset, and the effecter retained its old value.

It looks like it is working to me, please provide additional details on what is NOT Working in the issue.

**Comment by ibmzach** [comment]
Ok, I just didn't realize that the bit was embedded in the data parameter. Looks like it's working as intended.
