### ISSUE TITLE
libpldm/platform: Integrity check on uninitialized value in decode_get_sensor_reading_resp()

### ISSUE THREAD

**Issue by FHomps** [openbmc/pldm#28]
https://github.com/openbmc/pldm/blob/ef773059fdead2135c96c4a4c3520e4752012ef0/libpldm/platform.c#L1455:L1457

No comparison should be done on `*sensor_data_size`, which is supposed to be filled in by the function (and is, right after this check).

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc.org/c/openbmc/pldm/+/57716
