### ISSUE TITLE
lipldm/platform: incorrect value for PLDM_GET_SENSOR_READING_REQ_BYTES

### ISSUE THREAD

**Issue by FHomps** [openbmc/pldm#31]
https://github.com/openbmc/pldm/blob/master/libpldm/platform.h#L18
https://github.com/openbmc/pldm/blob/master/libpldm/platform.h#L756:L759
PLDM_GET_SENSOR_READING_REQ_BYTES should be defined to 3 instead of 4.
On a side note, I do not understand the need for those defines, compared to using `sizeof(struct pldm_get_sensor_reading_req)`. This is not an opaque structure, and this introduces new failure points, as evidenced by this issue. Is there a bigger picture need that I am missing here?

**Comment by ThuBaNguyen** [comment]
[*resolved*] in https://gerrit.openbmc.org/c/openbmc/pldm/+/54498
