### ISSUE TITLE
sd_bus_add_object_vtable: org.freedesktop.DBus.Error.InvalidArgs: Invalid argument

### ISSUE THREAD

**Issue by hanlei666-python** [openbmc/pldm#34]
- When I run the program in the terminal, it returns the following error:
:~/pldm/build$ sudo ./pldmd
terminate called after throwing an instance of 'sdbusplus::exception::SdBusError'
  what():  sd_bus_add_object_vtable: org.freedesktop.DBus.Error.InvalidArgs: Invalid argument
Aborted
and i found the error code is in here:
interface::interface(sdbusplus::bus_t& bus, const char* path,
                     const char* interf, const sdbusplus::vtable_t* vtable,
                     void* context) :
    _bus(get_busp(bus), bus.getInterface()),
    _path(path), _interf(interf), _intf(bus.getInterface()),
    _interface_added(false)
{
    sd_bus_slot* slot = nullptr;
    int r = _intf->sd_bus_add_object_vtable(
        get_busp(_bus), &slot, _path.c_str(), _interf.c_str(), vtable, context);
    if (r < 0)
    {
        throw exception::SdBusError(-r, "sd_bus_add_object_vtable");
    }

    _slot = std::move(slot);
}

**Comment by manojkiraneda** [comment]
@hanlei666-python can you give more information about the environment in which you are running pldm ?

**Comment by hanlei666-python** [comment]
> @hanlei666-python can you give more information about the environment in which you are running pldm ?
ok ,i am running the command in ubuntu20.0. and gcc-11 g++-11,cmake-3.18.0,ninja 1.10.2.git.kitware.jobserver-1,meson 0.63.0.
now ,i run this command again,but the error is:Could not open host EID file: /usr/local/share/pldm/host_eid
Failed to connect to the socket, RC= -111
and ,i find there is no pldm folder in /usr/local/share.

**Comment by manojkiraneda** [comment]
> @hanlei666-python can you give more information about the environment in which you are running pldm ?
> @manojkiraneda ok ,i am running the command in ubuntu20.0 virtual machine. and gcc-11 g++-11,cmake-3.18.0,ninja 1.10.2.git.kitware.jobserver-1,meson 0.63.0,Python 3.8.10 .
> now ,i run this command no sudo : ./pldmd,but the error is:Could not open host EID file: /usr/local/share/pldm/host_eid
> Failed to connect to the socket, RC= -111
> and ,i find there is no pldm folder in /usr/local/share.

openbmc/pldm repo is heavily dependent on the OpenBMC dependencies like object-manager , sdbusplus e.t.c . And its not really tested on desktop distor's like Ubuntu. 

And regarding 
> error is:Could not open host EID file: /usr/local/share/pldm/host_eid

This is a file that get's enabled when you enable `oem-ibm` meson option , please try the compilation with `meson build -Doem-ibm=enabled` , but with that said the pldm stack on ubuntu is not really tested & not guaranteed to work. Please use yocto.
