### ISSUE TITLE
Wrong check about an array in host-bmc/host_pdr_handler.cpp function getStateSensorReadingRespHandler 

### ISSUE THREAD

**Issue by desnudaenlaplaya** [openbmc/pldm#36]
I line:
https://github.com/openbmc/pldm/blob/68f5bbdfa5171f9a93ba13595251295e8a35f8fc/host-bmc/host_pdr_handler.cpp#L774
it's said:

```
if (sensorOffset > compositeSensorStates.size())
{
  std::cerr
  << " Error Invalid data, Invalid sensor offset"
  << std::endl;
  return;
}
```
but should be 
```
if ((compositeSensorStates.size()>1) && 
    (sensorOffset > (compositeSensorStates.size()-1)))
{
  std::cerr
  << " Error Invalid data, Invalid sensor offset"
  << std::endl;
  return;
}
```
because otherwise if array compositeSensorStates is size 4 for instance and sensorOffset=4 then compositeSensorStates[sensorOffset] will be out of bounds.

**Comment by lxwinspur** [comment]
Correct, @desnudaenlaplaya Could you push a new patch to fix it?

**Comment by manojkiraneda** [comment]
fixed by : https://gerrit.openbmc.org/c/openbmc/pldm/+/71041
