### ISSUE TITLE
Add supported PLDM types 

### ISSUE THREAD

**Issue by sampmisr** [openbmc/pldm#4]
change the following map to add the pldm types which are supported now (libpldmresponder: base.cpp)
static const std::map<Type, ver32_t> versions{
    {PLDM_BASE, {0xF1, 0xF0, 0xF0, 0x00}},
};

**Comment by dkodihal** [comment]
Fixed with https://github.com/openbmc/pldm/commit/74c1c1e5ee2a1013e8af7f84806b4b68cb3c29ae.
