### ISSUE TITLE
libpldm encode and decode APIs not consistent with each other

### ISSUE THREAD

**Issue by dkodihal** [openbmc/pldm#8]
The encode APIs work with a pldm_msg_t, but the decode APIs work with a specific member of pldm_msg_t (the payload). While the decode APIs only have to deal with the payload, they would be more consistent and it would be convenient for a caller to pass in pldm_msg_t.

This issue is to change all decode APIs to accept a `const struct pldm_msg *msg` instead of a `const uint8_t *msg`. The implementation of the decode API will have to work with `msg->payload` instead of `msg`.

**Comment by dkodihal** [comment]
@zaxxed can you work on this please?

**Comment by manojkiraneda** [comment]
@tomjoseph83 @dkodihal @sampmisr can we close this , as i see this has been unstreamed with  https://github.com/openbmc/pldm/commit/223a73d9b2961159498cd7ba15f592c0263121b5
