### ISSUE TITLE
PLDM commands list is not up to date

### ISSUE THREAD

**Issue by dkodihal** [openbmc/pldm#9]
https://github.com/openbmc/pldm/blob/master/libpldmresponder/base.cpp#L19 needs to be updated with currently implemented commands.

**Comment by dkodihal** [comment]
@zaxxed can you work on this please?

**Comment by SrideviRamesh** [comment]
Am fixing this in the commit https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/43861/
